export const NavigationStyles={
nevbar:"bg-custom-gradient-navigation fixed w-full z-50 top-0",
mobileContainer:"w-full lg:max-w-[85%] max-w-[90%] mx-auto flex items-center justify-between p-4",
navIcon:"flex md:hidden justify-start",
navIconMain:"text-white hover:text-[#0e86ff] cursor-pointer",
headingMain:"hidden md:flex items-center justify-end lg:gap-x-52 shrink-0 gap-x-6 w-full",
headingMap:"flex flex-row lg:space-x-10 space-x-4 font-medium",
headingLi:"flex  items-center",
headingAnchor:"relative block py-2 px-3 text-sm text-white after:content-[''] after:absolute after:left-0 after:bottom-0 after:h-[2px] after:bg-[#0e86ff] after:w-0 after:transition-all after:duration-300 hover:after:w-full",
navIconMobile:"text-white hover:text-[#0e86ff] cursor-pointer",
mobileMenuMain:"md:hidden fixed top-[57px] left-0 h-[calc(100vh-50px)] w-1/2 bg-custom-gradient backdrop-filter backdrop-blur-sm transition-transform duration-300 ease-in-out z-50",
isOpenMobileMenu:"translate-x-0",
isNotOpenMobileMenu:"-translate-x-full",
mobileHeadingMain:"flex flex-col items-center py-8 space-y-6 font-medium",
mobileHeadingLi:"flex w-full justify-start ml-20 items-center",
mobileHeadingAnchor:"block  px-3 text-sm text-white hover:text-[#0e86ff]",
border:"border-b-[1px] w-full border-[#8AFF84]",
backgroundOverlay:"md:hidden fixed inset-0 bg-black/30 backdrop-filter backdrop-blur-md z-40",

}