export const ServicesStyles={
renderSectionMain:"w-fit mb-10",
renderSectionTitle:"text-[20px] sm:text-[26px] md:text-[48px] font-bold mb-10 uppercase text-left w-fit bg-gradient-to-r from-[#8AFF84] to-[#1B7BFF] bg-clip-text text-transparent",
screenSizeLG_XL:"grid grid-cols-4 gap-10",
screenSizeNotLG_XL:"flex overflow-x-auto scrollbar-hide gap-4 px-4",
servicesMapMain:"flex flex-col items-start",
CardMain:"w-full flex flex-col items-center justify-center",
Card:"rounded-[7px] flex items-center justify-center",
cardTitle:"mt-4 font-semibold text-white text-center whitespace-nowrap",
servicesMain:"flex flex-col roboto-regular mt-15 mb-10 text-white",
renderSection:"px-4 md:px-10 lg:px-[97px] mt-10 text-left",
contentsMain:"w-full flex items-center justify-center mb-10",
contentMain2:"flex flex-col items-center w-full",
contentMain3:"flex w-full md:w-[60%] text-[16px] md:text-[20px] text-[#AFACAC] font-semibold md:mt-12 sm:mt-5 mt-5 justify-between",
contentBorder:"w-[95%] border-t-2 mt-4 border-[#8AFF84]",
scrollFooter:"mt-10",
footerMain:"w-full border-t-3 border-[#8AFF84] mt-0 flex flex-col items-center",
footer:"w-[90%] md:w-[83%]",

}