export const OurTeamStyles={
container:"flex flex-col mb-10 items-center gap-y-20 inter-custom justify-center",
main:"w-full flex justify-evenly mt-35 p-6",
header:"flex w-full flex-col items-start",
header2:"w-full justify-evenly items-center flex",
companyHeadBack:"w-[342px] h-[342px] bg-white rounded-full mb-7",
mainText:"text-[40px] space-x-3 font-bold flex",
turningText:"capitalize",
visionsText:"text-[#8AFF84] uppercase",
infoText:"lowercase",
realityText:"text-[#1B7BFF]",
aboutPara:"mt-10 text-[18px] font-medium leading-snug",
headMain:"text-[32px] leading-snug ml-40 roboto-regular",
headName:"font-normal",
headDesignation:"font-medium capitalize",
teamMemberContainer:"grid w-[77%] grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-y-12 justify-items-center",
teamMemberMain:"w-auto flex flex-col items-center",
notTeamPic:"w-[216px] h-[265px] bg-white rounded-[5px]",
teamPic:"w-[216px] h-[265px] rounded-[5px] object-cover",
teamMemberDetails:"text-center leading-tight mt-6 text-[20px]",
teamMemberName:"font-normal",
teamMemberDesignation:"font-medium w-full",
bottomBannerContainer:"w-full justify-center flex flex-col items-center",
bannerBackMain:"bg-cover roboto-regular flex-col bg-center w-full flex gap-y-0 items-center justify-center h-[60vh] min-h-[350px] max-h-[456px]",
beAPartText:"text-white mb-7 text-center px-4 text-2xl sm:text-3xl md:text-[64px] font-extrabold leading-tight dm-sans-regular",
exploreNewPossibilities:"text-[20px] mb-7",
joinUsText:"bg-gradient-to-r text-black px-14 py-2 rounded-xl cursor-pointer text-lg sm:text-[20px] shadow-[0px_4px_6px_rgba(138,255,132,0.6),0px_4px_6px_rgba(44,107,193,0.6)] from-[#8AFF84] to-[#2C6BC1] font-bold",
border:"w-full flex border-t-3 border-[#8AFF84] mt-0 flex-col items-center md:items-center",
footer:" w-[83%] flex flex-col",

}